version: '3.1'

volumes:
  dados: 
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: dblocal2
    ports:
      - 3308:3306
    volumes:
      # Volume de dados
      - dados:/var/lib/docker/volumes/dados
      #Scripts de inicialização
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql